blueprint:
  name: Beacon message frequency
  description: Creates a sensor which holds the message frequency for a bluetooth beacon
  domain: template
  input:
    uuid:
      name: uuid of bluetooth beacon
variables:
  input_uuid: !input uuid
trigger: 
  - trigger: event
    event_type: beacon_message
    alias: "beacon"
  - trigger: time_pattern
    minutes: "/1"
    alias: "time"
condition:
  - condition: template
    value_template: >
      {{ trigger.alias == "time" or (trigger.alias == "beacon" and trigger.event.data.uuid == input_uuid) }}
sensor:
  device_class: frequency
  state: >
    {% if trigger.alias == "beacon" %}
      {% set newValue = {'time' : as_timestamp(trigger.event.data.time) | int} %}
      {% set messageList = this.attributes.message_list | default([], true) + [newValue] %}
    {% else %}
      {% set messageList = this.attributes.message_list | default([], true) %}
    {% endif %}
    {% set newMessageList = messageList | selectattr('time', '>=', as_timestamp(now()) | int - 300) | list %}
    {{ newMessageList | length }}
  attributes:
    trigger_time: >
      {% if trigger.alias == "beacon" %}
        {{ trigger.event.data.time }}
      {% else %}
        {{ trigger.now }}
      {% endif %}
    trigger: >
      {{ trigger.alias }}
    last_reported_signal_strength: >
      {% if trigger.alias == "beacon" %}
        {{ trigger.event.data.rssi }}
      {% else %}
        {{ this.attributes.last_reported_signal_strength }}
      {% endif %}
    last_reported_signal_time: >
      {% if trigger.alias == "beacon" %}
        {{ trigger.event.data.time }}
      {% else %}
        {{ this.attributes.last_reported_signal_time }}
      {% endif %}
    message_list: >
      {% if trigger.alias == "beacon" %}
        {% set newValue = {'time' : as_timestamp(trigger.event.data.time) | int} %}
        {% set messageList = this.attributes.message_list | default([], true) + [newValue] %}
      {% else %}
        {% set messageList = this.attributes.message_list | default([], true) %}
      {% endif %}
      {% set newMessageList = messageList | selectattr('time', '>=', as_timestamp(now()) | int - 300) | list %}
      {{ newMessageList }}